---
- name: Add basics to the beacon cmdline_args
  ansible.builtin.set_fact:
    _prysm_beacon_internal_cmdline_args: >
      {{_prysm_beacon_internal_cmdline_args}}
      --{{prysm_network}}
      --datadir={{prysm_data_dir}}
      --verbosity={{prysm_log_level}}
      --log-file={{prysm_log_dir}}/beacon.log
      --log-format=json
      --jwt-secret={{prysm_jwt_auth_file}}
      --execution-endpoint={{prysm_execution_urls}}
      --accept-terms-of-use

- name: Add p2p settings to the beacon cmdline_args
  ansible.builtin.set_fact:
    _prysm_beacon_internal_cmdline_args: >
      {{_prysm_beacon_internal_cmdline_args}}
      --p2p-tcp-port={{prysm_p2p_port}}
      --p2p-udp-port={{prysm_p2p_port}}
      --p2p-host-ip='{{prysm_host_ip}}'
      --p2p-local-ip='{{prysm_local_ip}}'
  when: prysm_p2p_enabled|bool

- name: Add metrics to the beacon cmdline_args
  ansible.builtin.set_fact:
    _prysm_beacon_internal_cmdline_args: >
      {{_prysm_beacon_internal_cmdline_args}}
      --monitoring-host='{{ prysm_metrics_interface}}'
      --monitoring-port={{ prysm_metrics_port}}
  when: prysm_metrics_enabled|bool

- name: Add RPC to the beacon cmdline_args
  ansible.builtin.set_fact:
    _prysm_beacon_internal_cmdline_args: >
      {{_prysm_beacon_internal_cmdline_args}}
      --rpc-host='{{prysm_rpc_interface}}'
      --rpc-port={{prysm_rpc_port}}
      --grpc-gateway-corsdomain={{prysm_rpc_cors}}
      --grpc-gateway-host='{{prysm_rpc_interface}}'
      --grpc-gateway-port={{prysm_grpc_port}}
      --http-modules={{ prysm_http_modules }}
  when: prysm_rpc_enabled|bool

- name: Add fee receipt to the beacon cmdline_args
  ansible.builtin.set_fact:
    _prysm_beacon_internal_cmdline_args: >
      {{_prysm_beacon_internal_cmdline_args}}
      --suggested-fee-recipient={{prysm_default_fee_recipient}}
  when: prysm_default_fee_recipient != ""

- name: Add checkpoint sync to the beacon cmdline_args
  ansible.builtin.set_fact:
    _prysm_beacon_internal_cmdline_args: >
      {{_prysm_beacon_internal_cmdline_args}}
      --checkpoint-sync-url={{ prysm_checkpoint_sync_url }}
      --genesis-beacon-api-url={{ prysm_checkpoint_sync_url }}
  when: prysm_checkpoint_sync_url != ""

- name: Add genesis-state if defined
  ansible.builtin.set_fact:
    _prysm_beacon_internal_cmdline_args: >
      {{_prysm_beacon_internal_cmdline_args}}
      --genesis-state={{prysm_genesis_state}}
  when: prysm_genesis_state is defined and prysm_genesis_state != ""

- name: Add custom cli args if provided
  ansible.builtin.set_fact:
    _prysm_beacon_internal_cmdline_args: >
      {{_prysm_beacon_internal_cmdline_args}}
      {{ prysm_beacon_cmdline_args | join(' ') }}
  when: prysm_beacon_cmdline_args != []

- name: Sanitize beacon cmdline_args
  ansible.builtin.set_fact:
    _prysm_beacon_internal_cmdline_args: "{{_prysm_beacon_internal_cmdline_args | replace('\n', '') | replace('\"', '')}}"

- name: Show beacon cmdline_args
  ansible.builtin.debug:
    msg: "{{_prysm_beacon_internal_cmdline_args}}"

- name: Create prysm-beacon systemd service
  ansible.builtin.template:
    src: "prysm-beacon.service.j2"
    dest: "{{ prysm_systemd_dir }}/prysm-beacon.service"
    owner: "root"
    group: "root"
  become: true
  register: beacon_systemd_file

- name: Set updated optionally to trigger a systemd restart at the end
  ansible.builtin.set_fact:
    prysm_state_updates_beacon: "{{ prysm_state_updates_beacon + ['prysm.beacon_systemd_file'] }}"
  when: beacon_systemd_file is changed

- name: Reload systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true
  when: beacon_systemd_file is changed

- name: Enable and start prysm-beacon service
  ansible.builtin.systemd:
    name: prysm-beacon
    state: "{{ prysm_systemd_state }}"
    enabled: true
  become: true
  when: prysm_state_updates_beacon|length > 0
