---
- name: Ensure we have sane configuration
  block:
    - fail:
        msg: You must set "prysm_version" for this role to run
      when: prysm_version is not defined

# Retrive latest version when prysm_version == 'latest'
- name: Include task to retrieve latest version
  ansible.builtin.include_tasks: "latest.yml"
  when: prysm_version == 'latest'

- name: Get IP address to bind to if not provided
  include_tasks: "network.yml"
  when: not prysm_host_ip
  
- name: Install prysm
  include_tasks: "install.yml"

- name: Start beacon
  include_tasks: "beacon.yml"
  when: prysm_beacon_enabled

- name: Start validator
  include_tasks: "validator.yml"
  when: prysm_validator_enabled

- name: Set version info on a local file
  include_tasks: "tags.yml"
