---
- name: Get the default ipv4 address - and set this as the default fallback 
  set_fact:
    prysm_host_ip: >-
      {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] if
      hostvars[inventory_hostname]['ansible_default_ipv4']['address'] is
      defined else '127.0.0.1' }}
    
- name: Fetch public IP 
  uri:
    url: http://ifconfig.me/ip
    method: GET
    return_content: yes
    status_code: 200
  register: prysm_public_ip_output
  ignore_errors: True

- name: Set the host ip
  set_fact:
    prysm_host_ip: "{{ prysm_public_ip_output.content }}"
  when: prysm_public_ip_output.status == 200
