- name: Set the version on a local file so it can be used by other automation
  copy: 
    content: "{{ _prysm_version }}"
    dest: "{{ prysm_version_info_file }}"
    owner: "{{ prysm_user }}"
    group: "{{ prysm_group }}"
    mode: 0644    
  become: true    