---
- name: Add basics to the validator cmdline_args
  set_fact:
    prysm_validator_cmdline_args: >
      {{prysm_validator_cmdline_args}}
      --{{prysm_network}}
      --datadir={{prysm_validator_data_dir}}
      --wallet-dir={{ prysm_wallet_dir }}
      --wallet-password-file={{ prysm_wallet_password_file }}
      --beacon-rpc-provider={{ prysm_validator_beacon_interface }}
      --verbosity={{prysm_log_level}}
      --log-file={{prysm_log_dir}}/validator.log
      --log-format=json
      --jwt-secret={{prysm_jwt_auth_file}}
      --execution-endpoint={{prysm_execution_urls}}
      --enable-builder
      --accept-terms-of-use
      --enable-doppelganger
      --enable-external-slasher-protection
    
- name: Add metrics to the validator cmdline_args
  set_fact:
    prysm_validator_cmdline_args: >
      {{prysm_validator_cmdline_args}}
      --monitoring-host='{{ prysm_metrics_interface}}'
      --monitoring-port={{ prysm_validator_metrics_port}}
  when: prysm_metrics_enabled|bool == True

- name: Add RPC to the validator cmdline_args
  set_fact:
    prysm_validator_cmdline_args: >
      {{prysm_validator_cmdline_args}}
      --rpc-host='{{prysm_rpc_interface}}'
      --rpc-port={{prysm_rpc_port}}
      --grpc-gateway-corsdomain={{prysm_rpc_cors}}
      --grpc-gateway-host='{{prysm_rpc_interface}}'
      --grpc-gateway-port={{prysm_grpc_port}}
      --http-modules={{ prysm_http_modules }}
  when: prysm_rpc_enabled|bool == True

- name: Add graffiti to the validator cmdline_args
  set_fact:
    prysm_validator_cmdline_args: >
      {{prysm_validator_cmdline_args}}
      --graffiti={{prysm_graffiti}}
  when: prysm_graffiti != ""

- name: Add fee receipt to the validator cmdline_args
  set_fact:
    prysm_validator_cmdline_args: >
      {{prysm_validator_cmdline_args}}
      --suggested-fee-recipient={{prysm_default_fee_recipient}}
  when: prysm_default_fee_recipient != ""

- name: Add checkpoint sync to the validator cmdline_args
  set_fact:
    prysm_validator_cmdline_args: >
      {{prysm_validator_cmdline_args}}
      --checkpoint-sync-url={{ prysm_checkpoint_sync_url }}
      --genesis-validator-api-url={{ prysm_checkpoint_sync_url }}
  when: prysm_checkpoint_sync_url != ""

- name: Add genesis-state if defined
  set_fact:
    prysm_beacon_cmdline_args: >
      {{prysm_beacon_cmdline_args}}
      --genesis-state={{prysm_genesis_state}}
  when: prysm_genesis_state is defined and prysm_genesis_state != ""

- name: Add custom cli args if provided
  set_fact:
    prysm_validator_cmdline_args: >
      {{prysm_validator_cmdline_args}}
      {{ prysm_validator_custom_cmdline_args }}
  when: prysm_validator_custom_cmdline_args != ""

- name: Sanitize validator cmdline_args
  set_fact:
    prysm_validator_cmdline_args: "{{prysm_validator_cmdline_args | replace('\n', '') | replace('\"', '')}}"

- name: Show validator cmdline_args
  debug:
    msg: "{{prysm_validator_cmdline_args}}"

- name: Create prysm-validator systemd service
  template:
    src: "prysm-validator.service.j2"
    dest: "{{ prysm_systemd_dir }}/prysm-validator.service"
    owner: "root"
    group: "root"
  become: true
  register: validator_systemd_file

- name: Set updated optionally to trigger a systemd restart at the end
  set_fact:
    prysm_state_updates_validator: "{{ prysm_state_updates_validator + ['prysm.validator_systemd_file'] }}"
  when: validator_systemd_file is changed

- name: Reload systemd to reread configs
  systemd:
    daemon_reload: yes
  become: true
  when: validator_systemd_file is changed

- name: Enable and start prysm-validator service
  systemd:
    name: prysm-validator
    state: "{{ prysm_systemd_state }}"
    enabled: true
  become: true
  when: prysm_state_updates_validator|length > 0 
