---
- name: Add basics to the validator cmdline_args
  set_fact:
    prysm_validator_cmdline_args: >
      {{prysm_validator_cmdline_args}}
      --{{prysm_network}}
      --datadir={{prysm_validator_data_dir}}
      --wallet-dir={{ prysm_wallet_dir }}
      --wallet-password-file={{ prysm_wallet_password_file }}
      --beacon-rpc-provider={{ prysm_validator_beacon_interface }}
      --suggested-fee-recipient={{prysm_default_fee_recipient}}
      --verbosity={{prysm_log_level}}
      --log-file={{prysm_log_dir}}/validator.log
      --log-format=json
      --enable-builder
      --accept-terms-of-use
      --enable-doppelganger

- name: Add metrics to the validator cmdline_args
  set_fact:
    prysm_validator_cmdline_args: >
      {{prysm_validator_cmdline_args}}
      --monitoring-host='{{ prysm_metrics_interface}}'
      --monitoring-port={{ prysm_validator_metrics_port}}
  when: prysm_metrics_enabled|bool == True

- name: Add graffiti to the validator cmdline_args
  set_fact:
    prysm_validator_cmdline_args: >
      {{prysm_validator_cmdline_args}}
      --graffiti='{{prysm_graffiti}}'
  when: prysm_graffiti != ""

- name: Add custom cli args if provided
  set_fact:
    prysm_validator_cmdline_args: >
      {{prysm_validator_cmdline_args}}
      {{ prysm_validator_custom_cmdline_args }}
  when: prysm_validator_custom_cmdline_args != ""

- name: Sanitize validator cmdline_args
  set_fact:
    prysm_validator_cmdline_args: "{{prysm_validator_cmdline_args | replace('\n', '') | replace('\"', '')}}"

- name: Show validator cmdline_args
  debug:
    msg: "{{prysm_validator_cmdline_args}}"

- name: Create prysm-validator systemd service
  template:
    src: "prysm-validator.service.j2"
    dest: "{{ prysm_systemd_dir }}/prysm-validator.service"
    owner: "root"
    group: "root"
  become: true
  register: validator_systemd_file

- name: Set updated optionally to trigger a systemd restart at the end
  set_fact:
    prysm_state_updates_validator: "{{ prysm_state_updates_validator + ['prysm.validator_systemd_file'] }}"
  when: validator_systemd_file is changed

- name: Reload systemd to reread configs
  systemd:
    daemon_reload: yes
  become: true
  when: validator_systemd_file is changed

- name: Enable and start prysm-validator service
  systemd:
    name: prysm-validator
    state: "{{ prysm_systemd_state }}"
    enabled: true
  become: true
  when: prysm_state_updates_validator|length > 0 
